#pragma once

// ---------------------------------------------------------------------------
// Localized names for the Effect Display HUD module.
//
// Effect names follow the game's language setting: the module reads the
// `game_language` option out of the game's options.txt (see
// effectdisplay.cpp) and picks the matching table below, falling back to
// English. The strings are Mojang's own translations, generated by
// scripts/gen_effect_translations.py from:
//   * Bedrock Edition texts (github.com/Mojang/bedrock-samples,
//     resource_pack/texts) for the 29 languages Mojang ships, and
//   * Java Edition ar_sa.json (github.com/misode/mcmeta) for Arabic.
// Fatal Poison (Bedrock-only, no official lang key) and this module's own
// "Unknown Effect" fallback are translated inside that script.
//
// `systemFont` marks languages the bundled pixel font cannot render (it
// has no Arabic/CJK glyphs); those names are drawn with the launcher's
// default system font instead, which also shapes RTL text correctly. The
// flags are computed against resources/minecraft.ttf by the generator.
//
// Everything here is dependency-free so it can be unit tested without
// the game (see tests/effecti18n_test.cpp). Do not edit by hand —
// regenerate with scripts/gen_effect_translations.py.
// ---------------------------------------------------------------------------

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace bedrocktools::hud::effects {

// Number of effect slots per language, matching Bedrock's built-in effect
// ids; index 0 is the internal no-effect value and stays empty.
inline constexpr std::size_t kLocalizedEffectCount = 38;

struct EffectLanguage {
    const char* code;              // game language code, e.g. "en_US"
    const char* nativeName;        // label shown in the mod-menu picker
    bool systemFont;               // true -> draw with the system font
    const char* const effectNames[kLocalizedEffectCount];
    const char* infiniteDuration;  // label for endless effects
    const char* unknownEffect;     // fallback for unknown ids
};

// Index 0 is English (en_US): the universal fallback for unknown codes.
inline constexpr std::array<EffectLanguage, 30> kLanguages{{
    // en_US — English (US)
    { "en_US", "English (US)", false,
      {
        "", "Speed", "Slowness", "Haste",
        "Mining Fatigue", "Strength", "Instant Health", "Instant Damage",
        "Jump Boost", "Nausea", "Regeneration", "Resistance",
        "Fire Resistance", "Water Breathing", "Invisibility", "Blindness",
        "Night Vision", "Hunger", "Weakness", "Poison",
        "Wither", "Health Boost", "Absorption", "Saturation",
        "Levitation", "Fatal Poison", "Conduit Power", "Slow Falling",
        "Bad Omen", "Hero of the Village", "Darkness", "Trial Omen",
        "Wind Charged", "Weaving", "Oozing", "Infested",
        "Raid Omen", "Breath of the Nautilus",
      },
      "∞", "Unknown Effect" },
    // en_GB — English (UK)
    { "en_GB", "English (UK)", false,
      {
        "", "Speed", "Slowness", "Haste",
        "Mining Fatigue", "Strength", "Instant Health", "Instant Damage",
        "Jump Boost", "Nausea", "Regeneration", "Resistance",
        "Fire Resistance", "Water Breathing", "Invisibility", "Blindness",
        "Night Vision", "Hunger", "Weakness", "Poison",
        "Wither", "Health Boost", "Absorption", "Saturation",
        "Levitation", "Fatal Poison", "Conduit Power", "Slow Falling",
        "Bad Omen", "Hero of the Village", "Darkness", "Trial Omen",
        "Wind Charged", "Weaving", "Oozing", "Infested",
        "Raid Omen", "Breath of the Nautilus",
      },
      "∞", "Unknown Effect" },
    // de_DE — Deutsch
    { "de_DE", "Deutsch", false,
      {
        "", "Geschwindigkeit", "Langsamkeit", "Eile",
        "Abbaulähmung", "Stärke", "Direktheilung", "Direktschaden",
        "Sprungverst.", "Übelkeit", "Regeneration", "Resistenz",
        "Feuerresistenz", "Unterwasseratmung", "Unsichtbarkeit", "Blindheit",
        "Nachtsicht", "Hunger", "Schwäche", "Vergiftung",
        "Wither", "Gesundheitsbonus", "Absorption", "Sättigung",
        "Schwebekraft", "Tödliche Vergiftung", "Meereskraft", "Sanfter Fall",
        "Drohendes Unheil", "Dorfheld", "Dunkelheit", "Drohende Prüfung",
        "Windgeladen", "Weben", "Sickernd", "Befallen",
        "Überfall-Omen", "Nautilus-Atem",
      },
      "∞", "Unbekannter Effekt" },
    // es_ES — Español (ES)
    { "es_ES", "Español (ES)", false,
      {
        "", "Velocidad", "Lentitud", "Prisa",
        "Fatiga de extracción", "Fuerza", "Salud instantánea", "Daño instantáneo",
        "Impulso en salto", "Náuseas", "Regeneración", "Resistencia",
        "Resistente al fuego", "Respiración acuática", "Invisibilidad", "Ceguera",
        "Visión nocturna", "Hambre", "Debilidad", "Veneno",
        "Wither", "Mejora de salud", "Absorción", "Saturación",
        "Levitación", "Veneno fatal", "Poder del conducto", "Caída lenta",
        "Mal presagio", "Héroe de la aldea", "Oscuridad", "Presagio de prueba",
        "Con carga de viento", "Tejer", "Supuración", "Infestado",
        "Presagio de asalto", "Respiración de nautilo",
      },
      "∞", "Efecto desconocido" },
    // es_MX — Español (MX)
    { "es_MX", "Español (MX)", false,
      {
        "", "Velocidad", "Lentitud", "Prisa minera",
        "Fatiga de extracción", "Fuerza", "Salud instantánea", "Daño instantáneo",
        "Impulso en salto", "Náuseas", "Regeneración", "Resistencia",
        "Resistencia al fuego", "Respiración acuática", "Invisibilidad", "Ceguera",
        "Visión nocturna", "Hambre", "Debilidad", "Veneno",
        "Wither", "Salud mejorada", "Absorción", "Saturación",
        "Levitación", "Veneno fatal", "Poder de conducto", "Caída lenta",
        "Mal presagio", "Héroe de la aldea", "Oscuridad", "Presagio de prueba",
        "Con carga de viento", "Tejedura", "Exudación", "Infestado",
        "Presagio de asalto", "Respiración de nautilo",
      },
      "∞", "Efecto desconocido" },
    // fr_FR — Français (FR)
    { "fr_FR", "Français (FR)", false,
      {
        "", "Rapidité", "Lenteur", "Célérité",
        "Fatigue de minage", "Force", "Soin instantané", "Dégâts instantanés",
        "Sauts améliorés", "Nausée", "Régénération", "Résistance",
        "Résist. au feu", "Respiration aquatique", "Invisibilité", "Cécité",
        "Vision nocturne", "Faim", "Faiblesse", "Poison",
        "Décomposition", "Bonus de vie", "Absorption", "Saturation",
        "Lévitation", "Poison fatal", "Force de conduit", "Chute lente",
        "Mauvais présage", "Héros du village", "Obscurité", "Présage d'épreuve",
        "Souffle", "Tissage", "Viscosité", "Infestation",
        "Présage d'invasion", "Souffle du nautile",
      },
      "∞", "Effet inconnu" },
    // fr_CA — Français (CA)
    { "fr_CA", "Français (CA)", false,
      {
        "", "Rapidité", "Lenteur", "Célérité",
        "Épuisement", "Force", "Guérison instantanée", "Dégâts instantanés",
        "Sauts améliorés", "Nausée", "Régénération", "Résistance",
        "Résistance au feu", "Respiration aquatique", "Invisibilité", "Aveuglement",
        "Vision nocturne", "Faim", "Faiblesse", "Poison",
        "Décomposition", "Amélioration de santé", "Absorption", "Satiété",
        "Lévitation", "Poison fatal", "Énergie de conduit", "Chute lente",
        "Mauvais présage", "Héros du village", "Obscurité", "Présage d'épreuve",
        "Souffle", "Tissage", "Viscosité", "Infestation",
        "Présage d'invasion", "Respiration du nautile",
      },
      "∞", "Effet inconnu" },
    // it_IT — Italiano
    { "it_IT", "Italiano", false,
      {
        "", "Velocità", "Lentezza", "Sollecitudine",
        "Fatica del minatore", "Forza", "Salute istantanea", "Danno istantaneo",
        "Salto ampliato", "Nausea", "Rigenerazione", "Resistenza",
        "Resistenza al fuoco", "Apnea", "Invisibilità", "Cecità",
        "Visione notturna", "Fame", "Debolezza", "Avvelenamento",
        "Wither", "Salute ampliata", "Assorbimento", "Sazietà",
        "Levitazione", "Avvelenamento letale", "Energia condotta", "Caduta lenta",
        "Cattivo presagio", "Eroe del villaggio", "Oscurità", "Presagio di sfida",
        "Carica ventosa", "Tessitura", "Trasudazione", "Infestazione applicata",
        "Presagio d'incursione", "Respiro del nautilo",
      },
      "∞", "Effetto sconosciuto" },
    // ja_JP — 日本語
    { "ja_JP", "日本語", true,
      {
        "", "移動速度上昇", "移動速度低下", "採掘速度上昇",
        "採掘速度低下", "攻撃力上昇", "即時回復", "即時ダメージ",
        "跳躍力上昇", "吐き気", "再生能力", "耐性",
        "火炎耐性", "水中呼吸", "透明化", "暗闇",
        "暗視", "空腹", "弱体化", "毒",
        "ウィザー", "体力増強", "衝撃吸収", "満腹度回復",
        "浮遊", "致死毒", "コンジットパワー", "落下速度低下",
        "不吉な予感", "村の英雄", "暗闇", "試練の予感",
        "蓄風", "巣張り", "滲出", "虫食い",
        "襲撃の予感", "オウムガイの息吹",
      },
      "∞", "不明な効果" },
    // ko_KR — 한국어
    { "ko_KR", "한국어", true,
      {
        "", "속도", "속도 감소", "성급함",
        "채굴 피로", "힘", "즉시 치유", "즉시 피해",
        "점프 강화", "멀미", "재생", "저항",
        "화염 저항", "수중 호흡", "투명", "실명",
        "야간 투시", "허기", "나약함", "독",
        "시듦", "생명력 강화", "흡수", "포화",
        "공중 부양", "치명적인 독", "전달체의 힘", "느린 낙하",
        "흉조", "마을의 영웅", "어둠", "시련 징조",
        "돌풍", "방적", "점액화", "벌레 먹음",
        "습격 징조", "앵무조개의 숨결",
      },
      "∞", "알 수 없는 효과" },
    // pt_BR — Português (BR)
    { "pt_BR", "Português (BR)", false,
      {
        "", "Velocidade", "Lentidão", "Pressa",
        "Exaustão", "Força", "Vida Instantânea", "Dano Instantâneo",
        "Supersalto", "Náusea", "Regeneração", "Resistência",
        "Resistência ao Fogo", "Respiração Aquática", "Invisibilidade", "Cegueira",
        "Visão Noturna", "Fome", "Fraqueza", "Veneno",
        "Decomposição", "Vida Extra", "Absorção", "Saturação",
        "Levitação", "Veneno fatal", "Proteção do Mar", "Queda Lenta",
        "Mau Presságio", "Herói da Vila", "Escuridão", "Desafio de Presságio",
        "Ventania", "Tecelagem", "Gotejante", "Infestação",
        "Presságio de Invasão", "Fôlego de Náutilo",
      },
      "∞", "Efeito desconhecido" },
    // pt_PT — Português (PT)
    { "pt_PT", "Português (PT)", false,
      {
        "", "Velocidade", "Lentidão", "Rapidez",
        "Cansado de Minar", "Força", "Saúde Instantânea", "Danos Instantâneos",
        "Supersalto", "Náusea", "Regeneração", "Resistência",
        "Resistência ao Fogo", "Respiração Subaquática", "Invisibilidade", "Cegueira",
        "Visão Noturna", "Fome", "Fraqueza", "Veneno",
        "Wither", "Bónus de Vida", "Absorção", "Saturação",
        "Levitação", "Veneno fatal", "Poder de Canal", "Queda Lenta",
        "Mau Presságio", "Herói da Aldeia", "Escuridão", "Avaliação Sinistra",
        "Carregado de Vento", "Tecelagem", "Gotejante", "Infestado",
        "Presságio de Ataque", "Sopro do Náutilo",
      },
      "∞", "Efeito desconhecido" },
    // ru_RU — Русский
    { "ru_RU", "Русский", false,
      {
        "", "Скорость", "Медлительность", "Проворство",
        "Шахтерская усталость", "Сила", "Мгновенное оздоровление", "Моментальный урон",
        "Суперпрыжок", "Тошнота", "Регенерация", "Стойкость",
        "Огнестойкость", "Дыхание под водой", "Невидимость", "Слепота",
        "Ночное зрение", "Голод", "Слабость", "Отравление",
        "Иссушение", "Увеличение здоровья", "Поглощение", "Насыщенность",
        "Левитация", "Смертельное отравление", "Сила проводника", "Замедленное падение",
        "Дурное знамение", "Герой деревни", "Тьма", "Знамение испытания",
        "Ветровой заряд", "Ткачество", "Слизь", "Заражение",
        "Знамение налета", "Дыхание наутилуса",
      },
      "∞", "Неизвестный эффект" },
    // zh_CN — 简体中文
    { "zh_CN", "简体中文", true,
      {
        "", "速度", "缓慢", "急速",
        "开采疲劳", "力量", "瞬间治疗", "瞬间伤害",
        "跳跃增强", "反胃", "生命恢复", "抗性",
        "抗火", "水下呼吸", "隐身", "失明",
        "夜视", "饥饿", "虚弱", "中毒",
        "凋零", "生命提升", "伤害吸收", "饱和",
        "飘浮", "致命中毒", "潮涌能量", "缓降",
        "凶兆", "村庄英雄", "黑暗", "试炼之兆",
        "蓄风", "盘丝", "渗浆", "寄生",
        "袭击之兆", "鹦鹉螺之息",
      },
      "∞", "未知效果" },
    // zh_TW — 繁體中文
    { "zh_TW", "繁體中文", true,
      {
        "", "速度", "緩慢", "增速",
        "開採倦怠", "力量", "立即治療", "立即傷害",
        "跳躍增強", "噁心", "再生", "抗性",
        "抗火", "水下呼吸", "隱形", "失明",
        "夜視", "飢餓", "虛弱", "劇毒",
        "凋零", "生命值提升", "吸收", "飽和",
        "漂浮", "致命中毒", "水靈之力", "緩降",
        "不祥之兆", "村莊英雄", "黑暗", "試煉預兆",
        "蘊風", "編織", "滲液", "蛀蝕",
        "戰鬥預兆", "鸚鵡螺之息",
      },
      "∞", "未知效果" },
    // nl_NL — Nederlands
    { "nl_NL", "Nederlands", false,
      {
        "", "Snelheid", "Traagheid", "Haast",
        "Mijnmoeheid", "Kracht", "Onmiddellijke genezing", "Onmiddellijke schade",
        "Sprongkracht", "Misselijkheid", "Regeneratie", "Weerstand",
        "Vuurvast", "Wateradem", "Onzichtbaarheid", "Blindheid",
        "Nachtzicht", "Honger", "Zwakheid", "Vergif",
        "Wither", "Gezondheidsboost", "Absorptie", "Verzadiging",
        "Levitatie", "Dodelijk vergif", "Geleiderkracht", "Langzaam vallen",
        "Slecht voorteken", "Dorpsheld", "Duisternis", "Proefomen",
        "Getroffen door windvlaag", "Weven", "Druipen", "Geïnfesteerd",
        "Rooftocht voorteken", "Adem van de Nautilus",
      },
      "∞", "Onbekend effect" },
    // bg_BG — Български
    { "bg_BG", "Български", false,
      {
        "", "Скорост", "Забавяне", "Бързина",
        "Миньорска умора", "Сила", "Моментално лекуване", "Моментално нараняване",
        "Силен скок", "Гадене", "Регенерация", "Устойчивост",
        "Огнена устойчивост", "Подводно дишане", "Невидимост", "Слепота",
        "Нощно виждане", "Глад", "Слабост", "Отрова",
        "Чезнене", "Повишаване на здравето", "Поглъщане", "Наситеност",
        "Левитация", "Смъртоносна отрова", "Сила от проводник", "Бавно падане",
        "Лоша поличба", "Герой на Селото", "Мрак", "Поличба за изпитание",
        "С пълен вятърен заряд", "Тъкачество", "Слузливост", "Заразено",
        "Поличба за нашествие", "Дъхът от Наутилус",
      },
      "∞", "Непознат ефект" },
    // cs_CZ — Čeština
    { "cs_CZ", "Čeština", false,
      {
        "", "Rychlost", "Zpomalení", "Zrychlení",
        "Únava při těžbě", "Síla", "Okamžité uzdravení", "Okamžité poškození",
        "Posílení skoku", "Nevolnost", "Regenerace", "Odolnost",
        "Ohnivzdornost", "Dýchání pod vodou", "Neviditelnost", "Slepota",
        "Noční vidění", "Hlad", "Slabost", "Jed",
        "Pakostnice", "Posílení zdraví", "Pohlcení", "Sytost",
        "Levitace", "Smrtelná otrava", "Energie ze zářiče", "Pírko",
        "Špatné znamení", "Hrdina vesnice", "Temnota", "Zkušební znamení",
        "Větrem nabitý", "Tkaní", "Vytékající", "Ukrývající rybenku",
        "Znamení nájezdu", "Dech loděnky",
      },
      "∞", "Neznámý efekt" },
    // da_DK — Dansk
    { "da_DK", "Dansk", false,
      {
        "", "Hastighed", "Langsomhed", "Hast",
        "Minetræthed", "Styrke", "Hurtigt helbred", "Hurtig skade",
        "Superhop", "Kvalme", "Regenerering", "Modstand",
        "Ildmodstand", "Gæller", "Usynlighed", "Blindhed",
        "Nattesyn", "Sult", "Svaghed", "Gift",
        "Wither", "Helbredsboost", "Absorbering", "Mætning",
        "Levitation", "Dødelig forgiftning", "Fløderkraft", "Langsomt fald",
        "Dårligt tegn", "Landsbyens helt", "Mørke", "Prøvelsestegn",
        "Vindladet", "Vævning", "Siver", "Inficeret",
        "Plyndringstegn", "Nautilens ånde",
      },
      "∞", "Ukendt effekt" },
    // el_GR — Ελληνικά
    { "el_GR", "Ελληνικά", false,
      {
        "", "Ταχύτητα", "Βραδύτητα", "Βιασύνη",
        "Κόπωση εξόρυξης", "Δύναμη", "Άμεση υγεία", "Άμεση ζημιά",
        "Ενίσχυση άλματος", "Ναυτία", "Αναζωογόνηση", "Ανθεκτικότητα",
        "Ανθ/κότητα στη φωτιά", "Αναπνοή στο νερό", "Αφάνεια", "Τύφλωση",
        "Νυχτερινή όραση", "Πείνα", "Αδυναμία", "Δηλητήριο",
        "Μαρασμός", "Ενίσχυση υγείας", "Απορρόφηση", "Κορεσμός",
        "Αιώρηση", "Θανατηφόρο δηλητήριο", "Δύναμη αγωγού", "Επιβράδυνση πτώσης",
        "Κακός Οιωνός", "Ήρωας του Χωριού", "Σκοτάδι", "Δοκιμασία Οιωνός",
        "Επίθεση Ανέμου", "Ύφανση", "Αναβλύζει", "Με έντομο «ψαράκι»",
        "Οιωνός επιδρομής", "Ανάσα του Ναυτίλου",
      },
      "∞", "Άγνωστο εφέ" },
    // fi_FI — Suomi
    { "fi_FI", "Suomi", false,
      {
        "", "Nopeutus", "Hidastus", "Pikakaivuu",
        "Kaivuuhidastus", "Lisävoima", "Pikaparannus", "Pikavahinko",
        "Tehohyppy", "Yökötys", "Parantuminen", "Sietokyky",
        "Tulensieto", "Kidukset", "Näkymättömyys", "Sokeutus",
        "Pimeänäkö", "Nälkä", "Heiveröitys", "Myrkky",
        "Näivetys", "Kuntotehoste", "Imeytyminen", "Kyllästyminen",
        "Leijuminen", "Tappava myrkky", "Johdinvoima", "Tippuhidastus",
        "Huono enne", "Kylän sankari", "Pimeys", "Haaste-enne",
        "Tuulipanostettu", "Punominen", "Valuminen", "Saastunut",
        "Rynnäkköenne", "Helmiveneen henkäys",
      },
      "∞", "Tuntematon efekti" },
    // hu_HU — Magyar
    { "hu_HU", "Magyar", false,
      {
        "", "Gyorsaság", "Lassúság", "Sietség",
        "Bányászfáradtság", "Erő", "Azonnali életerő", "Azonnali sérülés",
        "Magasugrás", "Émelygés", "Regeneráció", "Ellenállás",
        "Tűzállóság", "Vízlégzés", "Láthatatlanság", "Vakság",
        "Éjjellátás", "Éhség", "Gyengeség", "Méreg",
        "Sorvasztó", "Életerősítés", "Elnyelt életerő", "Telítettség",
        "Lebegés", "Halálos méreg", "Csatornaeffektus", "Lassú zuhanás",
        "Rossz ómen", "A falu hőse", "Sötétség", "Próba-ómen",
        "Széllökés", "Hálószövés", "Nyálkaképzés", "Fertőzött",
        "Fosztogató-ómen", "A nautilusz lehelete",
      },
      "∞", "Ismeretlen hatás" },
    // id_ID — Bahasa Indonesia
    { "id_ID", "Bahasa Indonesia", false,
      {
        "", "Kecepatan", "Kelambatan", "Semangat",
        "Kelelahan Pertambangan", "Tenaga", "Kesehatan Instan", "Kerusakan Instan",
        "Meningkatkan Lompatan", "Mual", "Regenerasi", "Ketahanan",
        "Ketahanan Api", "Pernapasan Air", "Kemampuan Menghilang", "Kebutaan",
        "Penglihatan Malam", "Kelaparan", "Kelemahan", "Racun",
        "Wither", "Boost Kesehatan", "Penyerapan", "Saturasi",
        "Levitasi", "Racun fatal", "Kekuatan Konduit", "Jatuh Perlahan",
        "Pertanda Buruk", "Pahlawan Desa", "Kegelapan", "Pertanda Ujian",
        "Bertenaga Angin", "Menenun", "Mengalir", "Berisi",
        "Pertanda Buruk Serbuan", "Napas Nautilus",
      },
      "∞", "Efek tidak diketahui" },
    // nb_NO — Norsk
    { "nb_NO", "Norsk", false,
      {
        "", "Fart", "Treghet", "Hastverk",
        "Utvinningsutmattelse", "Styrke", "Øyeblikkelig helse", "Øyeblikkelig skade",
        "Hoppøkning", "Kvalme", "Regenerasjon", "Motstand",
        "Ildmotstand", "Vannpusting", "Usynlighet", "Blindhet",
        "Nattsyn", "Sult", "Svakhet", "Gift",
        "Wither", "Helseøkning", "Absorbering", "Metning",
        "Levitasjon", "Dødelig gift", "Vannkrefter", "Fjærfall",
        "Dårlig jærtegn", "Landsbyens helt", "Mørke", "Prøvelsesjærtegn",
        "Vindladet", "Vevende", "Tytende", "Befengt",
        "Plyndringsvarsel", "Perlebåtens åndedrett",
      },
      "∞", "Ukjent effekt" },
    // pl_PL — Polski
    { "pl_PL", "Polski", false,
      {
        "", "Szybkość", "Powolność", "Pośpiech",
        "Zmęczenie przy kopaniu", "Siła", "Natychmiastowe zdrowie", "Natychmiastowe obrażenia",
        "Wzmocnienie skoku", "Nudności", "Regeneracja", "Odporność",
        "Odporność na ogień", "Oddychanie pod wodą", "Niewidzialność", "Ślepota",
        "Widzenie w ciemności", "Głód", "Słabość", "Trucizna",
        "Obumieranie", "Wzmocnienie zdrowia", "Absorpcja", "Nasycenie",
        "Lewitacja", "Śmiertelna trucizna", "Moc przewodni", "Powolne opadanie",
        "Zły omen", "Bohater wioski", "Mrok", "Omen próby",
        "Z ładunkiem wiatru", "Tkanie", "Wyciekanie", "Zainfekowane",
        "Zwiastun najazdu", "Oddech łodzika",
      },
      "∞", "Nieznany efekt" },
    // sk_SK — Slovenčina
    { "sk_SK", "Slovenčina", false,
      {
        "", "Rýchlosť", "Pomalosť", "Zhon",
        "Únava z ťažby", "Sila", "Okamžité zdravie", "Okamžité poškodenie",
        "Lepší výskok", "Nevoľnosť", "Regenerácia", "Odolnosť",
        "Odolnosť proti ohňu", "Dýchanie vo vode", "Neviditeľnosť", "Slepota",
        "Nočné videnie", "Hlad", "Slabosť", "Jed",
        "Chradnutie", "Zlepšenie zdravia", "Absorpcia", "Nasýtenie",
        "Levitácia", "Smrteľná otrava", "Energia zo žiariča", "Pomalý pád",
        "Zlé znamenie", "Hrdina dediny", "Temnota", "Skúšobné znamenie",
        "Nabité vetrom", "Tkanie", "Bahnenie", "Zamorené",
        "Znamenie nájazdu", "Dych lodenky",
      },
      "∞", "Neznámy efekt" },
    // sv_SE — Svenska
    { "sv_SE", "Svenska", false,
      {
        "", "Hastighet", "Långsamhet", "Kvickhet",
        "Trötthet", "Styrka", "Omedelbar hälsa", "Omedelbar skada",
        "Hoppkraft", "Illamående", "Återhämtning", "Resistens",
        "Eldresistens", "Vattenandning", "Osynlighet", "Blindhet",
        "Mörkerseende", "Hunger", "Svaghet", "Gift",
        "Wither", "Hälsobonus", "Absorbering", "Mättnad",
        "Levitation", "Dödlig förgiftning", "Ledningskraft", "Långsamt fall",
        "Ond föraning", "Byns hjälte", "Mörker", "Föraning om utmaning",
        "Vindladdad", "Spinnande", "Slemmig", "Angripen",
        "Föraning om räd", "Pärlbåtsandning",
      },
      "∞", "Okänd effekt" },
    // tr_TR — Türkçe
    { "tr_TR", "Türkçe", false,
      {
        "", "Hız", "Yavaşlık", "Çabukluk",
        "Kazma Yorgunluğu", "Kuvvet", "Anında Sağlık", "Anında Hasar",
        "Zıplama Arttırma", "Bulantı", "Yenilenme", "Dayanıklılık",
        "Ateşe Dayanıklılık", "Suda Nefes Alma", "Görünmezlik", "Körlük",
        "Gece Görüşü", "Açlık", "Zayıflık", "Zehir",
        "Wither", "Sağlık Arttırıcı", "Emiş", "Doygunluk",
        "Havaya yükselme", "Ölümcül zehir", "Kanal Gücü", "Yavaş Düşme",
        "Kötü Kehanet", "Köyün Kahramanı", "Karanlık", "Serüven Kehaneti",
        "Rüzgar Saldırısı", "Dokuma", "Sızma", "Bulaşmış",
        "Baskın Kehaneti", "Notilus Nefesi",
      },
      "∞", "Bilinmeyen efekt" },
    // uk_UA — Українська
    { "uk_UA", "Українська", false,
      {
        "", "Швидкість", "Уповільнення", "Поспіх",
        "Втома від видобування", "Сила", "Миттєве одужання", "Миттєве пошкодження",
        "Стрибучість", "Нудота", "Відновлення", "Опір",
        "Вогнестійкість", "Дихання під водою", "Невидимість", "Сліпота",
        "Нічне бачення", "Голод", "Слабкість", "Отрута",
        "Згублення", "Покращення здоров’я", "Поглинання", "Насиченість",
        "Левітація", "Смертельна отрута", "Живлення від провідника", "Повільне падіння",
        "Погане знамення", "Сільський герой", "Темрява", "Знамення випробування",
        "Вихрова куля готова", "Ткацтво", "Заслизлення", "Заражено",
        "Ознака рейду", "Дихання наутилуса",
      },
      "∞", "Невідомий ефект" },
    // ar_SA — العربية
    { "ar_SA", "العربية", true,
      {
        "", "سرعة", "بطء", "عجل",
        "إجهاد التعدين", "قوّة", "صحة فوريّة", "ضرر فوري",
        "تعزيز القفز", "غثيان", "تجدد الصحة", "مقاومة",
        "مقاومة النار", "تنفس تحت المياه", "التخفي", "عمى",
        "الرؤية الليلية", "جوع", "ضعف", "سم",
        "الذبول", "تعزيز الصّحة", "امتصاص", "التشبع",
        "الطوفان", "سم قاتل", "قوة نواة المحيط", "سقوط بطيء",
        "تنبؤ سيء", "بطل القرية", "ظلام", "نحس الاختبار",
        "مشحون بالرياح", "النسيج", "ترشح", "الغزو",
        "تنبؤ الهجوم", "نَفَس النوتيلوس",
      },
      "∞", "تأثير غير معروف" },
}};

// Label of the mod-menu option that follows the game language.
inline constexpr const char* kAutoLanguageOption = "Auto";

// English is index 0 and doubles as the fallback for unknown ids/codes.
inline constexpr std::size_t kFallbackLanguage = 0;

inline std::size_t languageCount() { return kLanguages.size(); }

// Matches a game language code against the table: an exact code wins
// ("pt_BR"), otherwise the language part is tried ("ar_AE" -> Arabic,
// "ja" -> Japanese). Returns -1 when nothing matches.
inline int languageIndexForCode(std::string_view code) {
    if (code.empty()) return -1;
    for (std::size_t i = 0; i < kLanguages.size(); ++i) {
        if (code == kLanguages[i].code) return static_cast<int>(i);
    }
    const auto separator = code.find('_');
    const std::string_view base = separator == std::string_view::npos
        ? code : code.substr(0, separator);
    for (std::size_t i = 0; i < kLanguages.size(); ++i) {
        const std::string_view known = kLanguages[i].code;
        if (known.size() > base.size() && known.compare(0, base.size(), base) == 0
            && known[base.size()] == '_') {
            return static_cast<int>(i);
        }
    }
    return -1;
}

// Localized name of a status effect. Unknown or empty ids return the
// localized "Unknown Effect" fallback; gaps fall back to English.
inline const char* effectName(std::uint32_t effectId, std::size_t language) {
    if (language >= kLanguages.size()) language = kFallbackLanguage;
    const auto& lang = kLanguages[language];
    if (effectId == 0 || effectId >= kLocalizedEffectCount) return lang.unknownEffect;
    const char* name = lang.effectNames[effectId];
    if (name == nullptr || *name == '\0') name = kLanguages[kFallbackLanguage].effectNames[effectId];
    return name;
}

inline const char* infiniteDurationLabel(std::size_t language) {
    if (language >= kLanguages.size()) language = kFallbackLanguage;
    return kLanguages[language].infiniteDuration;
}

inline const char* unknownEffectLabel(std::size_t language) {
    if (language >= kLanguages.size()) language = kFallbackLanguage;
    return kLanguages[language].unknownEffect;
}

// True when this language must be drawn with the launcher's system font
// because the bundled pixel font has no glyphs for its script.
inline bool languageNeedsSystemFont(std::size_t language) {
    return language < kLanguages.size() && kLanguages[language].systemFont;
}

// Extracts the `game_language` value (e.g. "ar_SA") out of the contents
// of a Bedrock options.txt. Returns an empty view when the option is
// missing or empty (the game then follows the device default). Lines are
// `key:value`; both \n and \r\n endings are tolerated.
inline std::string_view parseGameLanguage(std::string_view fileContents) {
    std::string_view rest = fileContents;
    while (!rest.empty()) {
        auto lineEnd = rest.find('\n');
        std::string_view line = rest.substr(0, lineEnd);
        rest = lineEnd == std::string_view::npos ? std::string_view{} : rest.substr(lineEnd + 1);
        while (!line.empty() && (line.back() == '\r' || line.back() == ' ')) line.remove_suffix(1);
        while (!line.empty() && (line.front() == ' ' || line.front() == '\t')) line.remove_prefix(1);
        constexpr std::string_view kKey = "game_language:";
        if (line.size() > kKey.size() && line.substr(0, kKey.size()) == kKey) {
            std::string_view value = line.substr(kKey.size());
            while (!value.empty() && value.front() == ' ') value.remove_prefix(1);
            return value;
        }
    }
    return {};
}

} // namespace bedrocktools::hud::effects
